### PR TITLE
adding start and end strings for yoyodyne import.

### PR DESCRIPTION
**Pull request by bonham79**
Signed-off-by: bonham79 <travismbartley@gmail.com>

- Since it's not used except for downstream, I missed the lack of an End() class edit. Added back end with option to insert custom repr strings. 
- Not used in SED learning but added a Start() edit string back into the actions submodule. Can be used for future upgrades.
- Updated version.

### CODE REVIEW

**Comment by bonham79** [comment]
@kylebgorman Small fix but just want your eye in case it seems like an add that can be avoided. 

Also, would this count as a postfix or just new version update?

**Comment by bonham79** [comment]
Personal note: required fix for yoyodyne https://github.com/CUNY-CL/abstractness/issues/91

**Review by kylebgorman — COMMENTED** [review]
LGTM.

**Comment by kylebgorman** [comment]
> Also, would this count as a postfix or just new version update?

Strictly it's just adding functionality so postfix would be okay I think. I am not super careful about versioning beta software though...

**Pull request merged**
